-- Farm events, 9 Oct 2026: the goals of every league as public/event-goals.js has them now, changed in the LIVE harvest_event_pick
-- (only its list of goals; nothing else in the function moves). Two changes:
-- - A helping-hand stop rests an hour now (15 minutes before), so every league asks the Sprout League's helping-hand goals, at most
--   8 jobs or 2 rounds: two visits an hour apart within the 5 hours of an event (higher leagues asked up to 16 jobs and 4 rounds).
-- - Pickles join from the Meadow League (level 30): red cabbage and the pickle recipe both open at 15, and the cabbage alone grows
--   12 hours, so a farmer who had just reached 15 could not make one within an event.
-- scripts/event-goals-sql.mjs writes the same list into live-event-league-goals.sql. This file checks the live list first (exactly the
-- one live-event-league-goals.sql had before), makes 13 small edits to it (each must find its text once), checks the result is
-- exactly the new file's list, and stops otherwise. A second run says it is done already. Events already made keep their goals; the
-- next ones get the new ones.
do $do$
declare def text:=pg_get_functiondef('public.harvest_event_pick(bigint)'::regprocedure); a int; b int; pools text;
begin
 a:=position('pools constant jsonb:=''' in def)+length('pools constant jsonb:=''');
 b:=position(E''';\n' in substr(def,a));
 pools:=substr(def,a,b-1);
 if md5(pools)='61ba0b0ff5828cd162181d10a08e1b52' then raise notice 'harvest_event_pick has the new goals already'; return; end if;
 if md5(pools)<>'64d40ac547d86f16f33c90c515a63a2d' then raise exception 'harvest_event_pick is not the one this file expects; read the live definition before changing it'; end if;
 if (length(pools)-length(replace(pools,'ice."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_pickles","targets":[1,2,3],"titles":[["Pickle jars","Red cabbage into crisp pickles."],["In a jar","Pickles for the winter shelves."]]},{"stat":"made_fertilizer","targets":[6,9,15],"titles":','')))/length('ice."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_pickles","targets":[1,2,3],"titles":[["Pickle jars","Red cabbage into crisp pickles."],["In a jar","Pickles for the winter shelves."]]},{"stat":"made_fertilizer","targets":[6,9,15],"titles":')<>1 then raise exception 'edit 1: its text is not in the live list once'; end if;
 pools:=replace(pools,'ice."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_pickles","targets":[1,2,3],"titles":[["Pickle jars","Red cabbage into crisp pickles."],["In a jar","Pickles for the winter shelves."]]},{"stat":"made_fertilizer","targets":[6,9,15],"titles":','ice."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_fertilizer","targets":[6,9,15],"titles":');
 if (length(pools)-length(replace(pools,'ities","targets":[3,6,9],"titles":[["A help','')))/length('ities","targets":[3,6,9],"titles":[["A help')<>1 then raise exception 'edit 2: its text is not in the live list once'; end if;
 pools:=replace(pools,'ities","targets":[3,6,9],"titles":[["A help','ities","targets":[3,5,8],"titles":[["A help');
 if (length(pools)-length(replace(pools,'ckles","targets":[1,3,4],"titles":[["Pickle','')))/length('ckles","targets":[1,3,4],"titles":[["Pickle')<>1 then raise exception 'edit 3: its text is not in the live list once'; end if;
 pools:=replace(pools,'ckles","targets":[1,3,4],"titles":[["Pickle','ckles","targets":[1,2,3],"titles":[["Pickle');
 if (length(pools)-length(replace(pools,'ivities","targets":[4,7,11],"titles":[["A help','')))/length('ivities","targets":[4,7,11],"titles":[["A help')<>1 then raise exception 'edit 4: its text is not in the live list once'; end if;
 pools:=replace(pools,'ivities","targets":[4,7,11],"titles":[["A help','ivities","targets":[3,5,8],"titles":[["A help');
 if (length(pools)-length(replace(pools,'nds","targets":[1,1,3],"titles":[["Grand ','')))/length('nds","targets":[1,1,3],"titles":[["Grand ')<>1 then raise exception 'edit 5: its text is not in the live list once'; end if;
 pools:=replace(pools,'nds","targets":[1,1,3],"titles":[["Grand ','nds","targets":[1,1,2],"titles":[["Grand ');
 if (length(pools)-length(replace(pools,'tles":[["Veggie boxes","Pack your vegetables for a better price."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_pickles","targets":[2,3,5],"titles":[["Pickle jars","Red cabbage into crisp pickles."],["In a jar","Pickles for the winter shelves."]]},{"stat":"made_fertilizer","targets":[9,14,25],"ti','')))/length('tles":[["Veggie boxes","Pack your vegetables for a better price."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_pickles","targets":[2,3,5],"titles":[["Pickle jars","Red cabbage into crisp pickles."],["In a jar","Pickles for the winter shelves."]]},{"stat":"made_fertilizer","targets":[9,14,25],"ti')<>1 then raise exception 'edit 6: its text is not in the live list once'; end if;
 pools:=replace(pools,'tles":[["Veggie boxes","Pack your vegetables for a better price."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_pickles","targets":[2,3,5],"titles":[["Pickle jars","Red cabbage into crisp pickles."],["In a jar","Pickles for the winter shelves."]]},{"stat":"made_fertilizer","targets":[9,14,25],"ti','tles":[["Veggie boxes","Pack your vegetables for a better price."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_pickles","targets":[1,3,4],"titles":[["Pickle jars","Red cabbage into crisp pickles."],["In a jar","Pickles for the winter shelves."]]},{"stat":"made_fertilizer","targets":[9,14,25],"ti');
 if (length(pools)-length(replace(pools,'ivities","targets":[5,8,12],"titles":[["A help','')))/length('ivities","targets":[5,8,12],"titles":[["A help')<>1 then raise exception 'edit 7: its text is not in the live list once'; end if;
 pools:=replace(pools,'ivities","targets":[5,8,12],"titles":[["A help','ivities","targets":[3,5,8],"titles":[["A help');
 if (length(pools)-length(replace(pools,'rades","targets":[1,3,4],"titles":[["Builders’ day","Make your buildings better and faster."],["Hammer time","Upgrade the buildings that work hardest for you."]]},{"stat":"activity_rounds","targets":[2,2,3],"titles":[["Grand tour","Help at all four stops for the round bonus."],["All around","The greenhouse, the apiary, the paddock and the workshop, in one round."]]},{"stat":"tractor","targets":[4,7,11]','')))/length('rades","targets":[1,3,4],"titles":[["Builders’ day","Make your buildings better and faster."],["Hammer time","Upgrade the buildings that work hardest for you."]]},{"stat":"activity_rounds","targets":[2,2,3],"titles":[["Grand tour","Help at all four stops for the round bonus."],["All around","The greenhouse, the apiary, the paddock and the workshop, in one round."]]},{"stat":"tractor","targets":[4,7,11]')<>1 then raise exception 'edit 8: its text is not in the live list once'; end if;
 pools:=replace(pools,'rades","targets":[1,3,4],"titles":[["Builders’ day","Make your buildings better and faster."],["Hammer time","Upgrade the buildings that work hardest for you."]]},{"stat":"activity_rounds","targets":[2,2,3],"titles":[["Grand tour","Help at all four stops for the round bonus."],["All around","The greenhouse, the apiary, the paddock and the workshop, in one round."]]},{"stat":"tractor","targets":[4,7,11]','rades","targets":[1,3,4],"titles":[["Builders’ day","Make your buildings better and faster."],["Hammer time","Upgrade the buildings that work hardest for you."]]},{"stat":"activity_rounds","targets":[1,1,2],"titles":[["Grand tour","Help at all four stops for the round bonus."],["All around","The greenhouse, the apiary, the paddock and the workshop, in one round."]]},{"stat":"tractor","targets":[4,7,11]');
 if (length(pools)-length(replace(pools,'ivities","targets":[5,9,14],"titles":[["A help','')))/length('ivities","targets":[5,9,14],"titles":[["A help')<>1 then raise exception 'edit 9: its text is not in the live list once'; end if;
 pools:=replace(pools,'ivities","targets":[5,9,14],"titles":[["A help','ivities","targets":[3,5,8],"titles":[["A help');
 if (length(pools)-length(replace(pools,'rades","targets":[1,3,4],"titles":[["Builders’ day","Make your buildings better and faster."],["Hammer time","Upgrade the buildings that work hardest for you."]]},{"stat":"activity_rounds","targets":[2,2,3],"titles":[["Grand tour","Help at all four stops for the round bonus."],["All around","The greenhouse, the apiary, the paddock and the workshop, in one round."]]},{"stat":"tractor","targets":[5,8,12]','')))/length('rades","targets":[1,3,4],"titles":[["Builders’ day","Make your buildings better and faster."],["Hammer time","Upgrade the buildings that work hardest for you."]]},{"stat":"activity_rounds","targets":[2,2,3],"titles":[["Grand tour","Help at all four stops for the round bonus."],["All around","The greenhouse, the apiary, the paddock and the workshop, in one round."]]},{"stat":"tractor","targets":[5,8,12]')<>1 then raise exception 'edit 10: its text is not in the live list once'; end if;
 pools:=replace(pools,'rades","targets":[1,3,4],"titles":[["Builders’ day","Make your buildings better and faster."],["Hammer time","Upgrade the buildings that work hardest for you."]]},{"stat":"activity_rounds","targets":[2,2,3],"titles":[["Grand tour","Help at all four stops for the round bonus."],["All around","The greenhouse, the apiary, the paddock and the workshop, in one round."]]},{"stat":"tractor","targets":[5,8,12]','rades","targets":[1,3,4],"titles":[["Builders’ day","Make your buildings better and faster."],["Hammer time","Upgrade the buildings that work hardest for you."]]},{"stat":"activity_rounds","targets":[1,1,2],"titles":[["Grand tour","Help at all four stops for the round bonus."],["All around","The greenhouse, the apiary, the paddock and the workshop, in one round."]]},{"stat":"tractor","targets":[5,8,12]');
 if (length(pools)-length(replace(pools,'ckles","targets":[2,4,6],"titles":[["Pickle','')))/length('ckles","targets":[2,4,6],"titles":[["Pickle')<>1 then raise exception 'edit 11: its text is not in the live list once'; end if;
 pools:=replace(pools,'ckles","targets":[2,4,6],"titles":[["Pickle','ckles","targets":[2,3,5],"titles":[["Pickle');
 if (length(pools)-length(replace(pools,'ivities","targets":[6,10,16],"titles":[["A help','')))/length('ivities","targets":[6,10,16],"titles":[["A help')<>1 then raise exception 'edit 12: its text is not in the live list once'; end if;
 pools:=replace(pools,'ivities","targets":[6,10,16],"titles":[["A help','ivities","targets":[3,5,8],"titles":[["A help');
 if (length(pools)-length(replace(pools,'_rounds","targets":[2,2,4],"titles":[["Grand ','')))/length('_rounds","targets":[2,2,4],"titles":[["Grand ')<>1 then raise exception 'edit 13: its text is not in the live list once'; end if;
 pools:=replace(pools,'_rounds","targets":[2,2,4],"titles":[["Grand ','_rounds","targets":[1,1,2],"titles":[["Grand ');
 if md5(pools)<>'61ba0b0ff5828cd162181d10a08e1b52' then raise exception 'the new goals do not come out as public/event-goals.js has them'; end if;
 execute overlay(def placing pools from a for b-1);
end $do$;
