-- Farm events, 10 Oct 2026 (the owner's pick from the balance review): goals that almost nobody could finish now fit, changed in the
-- LIVE harvest_event_pick (only its list of goals; nothing else in the function moves). public/event-goals.js has the same list and
-- scripts/event-goals-sql.mjs writes it into live-event-league-goals.sql.
-- - Helping hand: a medium goal is 4 jobs, one visit to all four stops (a stop rests an hour since 9 Oct).
-- - Eight building goals (juice, orchard juice, smoothie, compote, preserves, pickled beans, truffles, truffle omelette) join from
--   the Orchard League (45) instead of the Meadow League (30), and yarn and cloth from the Harvest League (60) instead of 45.
-- - Sprout: vegetable boxes join from the Meadow League; cauliflower, fertilizer and diamonds spent ask less.
-- It checks the live list first (exactly the one this repo had on 9 Oct), makes 70 small edits, and applies the result only
-- when it is exactly the new list (md5); otherwise it stops and nothing changes. A second run says it is done already. Events already
-- made keep their goals; the next ones get the new ones.
do $do$
declare def text:=pg_get_functiondef('public.harvest_event_pick(bigint)'::regprocedure); a int; b int; pools text;
begin
 a:=position('pools constant jsonb:=''' in def)+length('pools constant jsonb:=''');
 b:=position(E''';\n' in substr(def,a));
 pools:=substr(def,a,b-1);
 if md5(pools)='badc8ae11b1bba4dcaf6b69cc21f5f62' then raise notice 'harvest_event_pick has the new goals already'; return; end if;
 if md5(pools)<>'61ba0b0ff5828cd162181d10a08e1b52' then raise exception using message='harvest_event_pick is not the one this file expects; read the live definition before changing it'; end if;
 pools:=replace(pools,'7,10],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,5,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm','7,10],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,4,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm');
 pools:=replace(pools,'700],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,20,40],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","tar','700],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,10,20],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","tar');
 pools:=replace(pools,'h","targets":[2,3,5],"titles":[["','h","targets":[1,3,4],"titles":[["');
 pools:=replace(pools,'n","targets":[6,12,18],"titles":[["','n","targets":[5,11,16],"titles":[["');
 pools:=replace(pools,'s","targets":[10,17,25],"titles":[["','s","targets":[9,15,20],"titles":[["');
 pools:=replace(pools,'ves","targets":[3,5,9],"titles":[["Preser','ves","targets":[3,5,8],"titles":[["Preser');
 pools:=replace(pools,'juice","targets":[5,10,16],"titles":[["Orchar','juice","targets":[5,9,14],"titles":[["Orchar');
 pools:=replace(pools,'ice","targets":[3,5,9],"titles":[["Pressi','ice","targets":[3,5,8],"titles":[["Pressi');
 pools:=replace(pools,'lette","targets":[3,7,10],"titles":[["Truffl','lette","targets":[3,6,9],"titles":[["Truffl');
 pools:=replace(pools,'s":[3,5,9],"title','s":[3,5,8],"title');
 pools:=replace(pools,'othie","targets":[3,7,10],"titles":[["Smooth','othie","targets":[3,6,9],"titles":[["Smooth');
 pools:=replace(pools,'s","targets":[4,8,12],"titles":[["','s","targets":[2,3,5],"titles":[["');
 pools:=replace(pools,'r","targets":[12,20,30],"titles":[[','r","targets":[8,12,20],"titles":[[');
 pools:=replace(pools,'tilized","targets":[5,9,14],"titles":[["Rich s','tilized","targets":[4,5,9],"titles":[["Rich s');
 pools:=replace(pools,',6,8],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,5,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm',',6,8],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,4,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm');
 pools:=replace(pools,'600],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,20,40],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","tar','600],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,10,20],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","tar');
 pools:=replace(pools,'les":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","targets":[1,3,4],"titles":[["Fine cloth","Weave yarn into fine cloth."],["The loom","Thread by thread, roll by roll."]]},{"stat":"made_squashsoup","targets":[1','les":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","targets":[1,2,4],"titles":[["Fine cloth","Weave yarn into fine cloth."],["The loom","Thread by thread, roll by roll."]]},{"stat":"made_squashsoup","targets":[1');
 pools:=replace(pools,',20],"titles":[["Shearing day","Soft wool from the Sheep Barn."],["Woolly flock","A good day for the shears."]]},{"stat":"made_yarn","targets":[5,11,16],"titles":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","target',',20],"titles":[["Shearing day","Soft wool from the Sheep Barn."],["Woolly flock","A good day for the shears."]]},{"stat":"made_yarn","targets":[5,9,14],"titles":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","target');
 pools:=replace(pools,'erve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[9,15,20],"titles":[["Truffle hunt","Let the pigs find truffles at the Pig Farm."],["Clever noses","Truffles, deep in the soil."]]},{"stat":"made_honey","targets":[11','erve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[8,13,19],"titles":[["Truffle hunt","Let the pigs find truffles at the Pig Farm."],["Clever noses","Truffles, deep in the soil."]]},{"stat":"made_honey","targets":[11');
 pools:=replace(pools,'gets":[5,9,14],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[3,5,8],"titles":[["Preserve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[8,13,1','gets":[5,9,14],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[3,4,7],"titles":[["Preserve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[8,13,1');
 pools:=replace(pools,',8],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","targets":[5,9,14],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[3,4',',8],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","targets":[4,8,12],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[3,4');
 pools:=replace(pools,'3,6,9],"titles":[["Stew pot","Slow-cooked stew from the Farm Kitchen."],["Supper time","Hearty bowls for hungry farmers."]]},{"stat":"made_applejuice","targets":[3,5,8],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","target','3,6,9],"titles":[["Stew pot","Slow-cooked stew from the Farm Kitchen."],["Supper time","Hearty bowls for hungry farmers."]]},{"stat":"made_applejuice","targets":[3,4,7],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","target');
 pools:=replace(pools,'4],"titles":[["Orchard salad","Fruit and greens from the Packing Shed."],["Fresh from the trees","A colourful salad from the orchard."]]},{"stat":"made_truffleomelette","targets":[3,6,9],"titles":[["Truffle breakfast","Truffles and eggs into a fine omelette."],["Chef’s special","The Farm Kitchen’s finest breakfast."]]},{"stat":"made_berrycheesecake","targets":[1,3,','4],"titles":[["Orchard salad","Fruit and greens from the Packing Shed."],["Fresh from the trees","A colourful salad from the orchard."]]},{"stat":"made_truffleomelette","targets":[3,5,8],"titles":[["Truffle breakfast","Truffles and eggs into a fine omelette."],["Chef’s special","The Farm Kitchen’s finest breakfast."]]},{"stat":"made_berrycheesecake","targets":[1,3,');
 pools:=replace(pools,',8],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[2,3,5],"titles":[["Bean jars","Green beans into pickled beans."],["Snap and crunch","Pickled beans for the shelves."]]},{"stat":"made_orchardsalad","targets":[5,9,',',8],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,3,4],"titles":[["Bean jars","Green beans into pickled beans."],["Snap and crunch","Pickled beans for the shelves."]]},{"stat":"made_orchardsalad","targets":[5,9,');
 pools:=replace(pools,'"Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[3,5,8],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,','"Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[3,4,7],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,');
 pools:=replace(pools,'"titles":[["Apple pie day","Apples and flour into warm apple pie."],["Pie in the oven","The smell of apple pie across the valley."]]},{"stat":"made_berrysmoothie","targets":[3,6,9],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[3,4,7],','"titles":[["Apple pie day","Apples and flour into warm apple pie."],["Pie in the oven","The smell of apple pie across the valley."]]},{"stat":"made_berrysmoothie","targets":[3,5,8],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[3,4,7],');
 pools:=replace(pools,'etables","targets":[3,7,10],"titles":[["Veggie','etables","targets":[2,3,5],"titles":[["Veggie');
 pools:=replace(pools,'r","targets":[10,17,25],"titles":[["','r","targets":[7,10,17],"titles":[["');
 pools:=replace(pools,'rgets":[5,8,13],"title','rgets":[3,5,8],"title');
 pools:=replace(pools,',5,7],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,5,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm',',5,7],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,4,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm');
 pools:=replace(pools,'000],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,20,40],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","tar','000],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,10,20],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","tar');
 pools:=replace(pools,'s":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","targets":[1,2,4],"titles":[["Fine cloth","Weave yarn into fine cloth."],["The loom","Thread by thread, roll by roll."]]},{"stat":"made_squashsoup","targets":[1,2','s":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","targets":[1,2,3],"titles":[["Fine cloth","Weave yarn into fine cloth."],["The loom","Thread by thread, roll by roll."]]},{"stat":"made_squashsoup","targets":[1,2');
 pools:=replace(pools,'12,18],"titles":[["Shearing day","Soft wool from the Sheep Barn."],["Woolly flock","A good day for the shears."]]},{"stat":"made_yarn","targets":[5,9,14],"titles":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","target','12,18],"titles":[["Shearing day","Soft wool from the Sheep Barn."],["Woolly flock","A good day for the shears."]]},{"stat":"made_yarn","targets":[4,8,12],"titles":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","target');
 pools:=replace(pools,'erve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[8,13,19],"titles":[["Truffle hunt","Let the pigs find truffles at the Pig Farm."],["Clever noses","Truffles, deep in the soil."]]},{"stat":"made_honey","targets":[9,','erve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[7,12,16],"titles":[["Truffle hunt","Let the pigs find truffles at the Pig Farm."],["Clever noses","Truffles, deep in the soil."]]},{"stat":"made_honey","targets":[9,');
 pools:=replace(pools,'argets":[4,8,12],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[3,4,7],"titles":[["Preserve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[7,12,1','argets":[4,8,12],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[2,3,6],"titles":[["Preserve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[7,12,1');
 pools:=replace(pools,',7],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","targets":[4,8,12],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[2,3',',7],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","targets":[3,7,10],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[2,3');
 pools:=replace(pools,'8],"titles":[["Stew pot","Slow-cooked stew from the Farm Kitchen."],["Supper time","Hearty bowls for hungry farmers."]]},{"stat":"made_applejuice","targets":[3,4,7],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","','8],"titles":[["Stew pot","Slow-cooked stew from the Farm Kitchen."],["Supper time","Hearty bowls for hungry farmers."]]},{"stat":"made_applejuice","targets":[2,3,6],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","');
 pools:=replace(pools,',12],"titles":[["Orchard salad","Fruit and greens from the Packing Shed."],["Fresh from the trees","A colourful salad from the orchard."]]},{"stat":"made_truffleomelette","targets":[3,5,8],"titles":[["Truffle breakfast","Truffles and eggs into a fine omelette."],["Chef’s special","The Farm Kitchen’s finest breakfast."]]},{"stat":"made_berrycheesecake","targets":[1,2,',',12],"titles":[["Orchard salad","Fruit and greens from the Packing Shed."],["Fresh from the trees","A colourful salad from the orchard."]]},{"stat":"made_truffleomelette","targets":[2,5,7],"titles":[["Truffle breakfast","Truffles and eggs into a fine omelette."],["Chef’s special","The Farm Kitchen’s finest breakfast."]]},{"stat":"made_berrycheesecake","targets":[1,2,');
 pools:=replace(pools,'],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,3,4],"titles":[["Bean jars","Green beans into pickled beans."],["Snap and crunch","Pickled beans for the shelves."]]},{"stat":"made_orchardsalad","targets":[4,8,','],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,2,3],"titles":[["Bean jars","Green beans into pickled beans."],["Snap and crunch","Pickled beans for the shelves."]]},{"stat":"made_orchardsalad","targets":[4,8,');
 pools:=replace(pools,'tles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[3,4,7],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,2,3],"','tles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[2,3,6],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,2,3],"');
 pools:=replace(pools,'les":[["Apple pie day","Apples and flour into warm apple pie."],["Pie in the oven","The smell of apple pie across the valley."]]},{"stat":"made_berrysmoothie","targets":[3,5,8],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[2','les":[["Apple pie day","Apples and flour into warm apple pie."],["Pie in the oven","The smell of apple pie across the valley."]]},{"stat":"made_berrysmoothie","targets":[2,5,7],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[2');
 pools:=replace(pools,'etables","targets":[3,6,9],"titles":[["Veggie','etables","targets":[1,3,4],"titles":[["Veggie');
 pools:=replace(pools,'r","targets":[9,15,25],"titles":[[','r","targets":[6,9,15],"titles":[[');
 pools:=replace(pools,'d","targets":[4,7,11],"titles":[["','d","targets":[3,4,7],"titles":[["');
 pools:=replace(pools,',4,6],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,5,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm',',4,6],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,4,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm');
 pools:=replace(pools,'900],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,20,40],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","tar','900],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,10,20],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","tar');
 pools:=replace(pools,',10,16],"titles":[["Shearing day","Soft wool from the Sheep Barn."],["Woolly flock","A good day for the shears."]]},{"stat":"made_yarn","targets":[4,8,12],"titles":[["Spin it","Wool into yarn at the Weaving Shed."],["Round and round","The spinning wheel never stops."]]},{"stat":"made_cloth","targets":[1,2,3],"titles":[["Fine cloth","Weave yarn into fine cloth."],["The loom","Thread by thread, roll by roll."]]},{"stat":"made_squashsoup","targets":[1,2,3],"titles":[["Soup kitchen","Warm squash soup for the valley."',',10,16],"titles":[["Shearing day","Soft wool from the Sheep Barn."],["Woolly flock","A good day for the shears."]]},{"stat":"made_squashsoup","targets":[1,2,3],"titles":[["Soup kitchen","Warm squash soup for the valley."');
 pools:=replace(pools,'erve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[7,12,16],"titles":[["Truffle hunt","Let the pigs find truffles at the Pig Farm."],["Clever noses","Truffles, deep in the soil."]]},{"stat":"made_honey","targets":[8,','erve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[6,10,14],"titles":[["Truffle hunt","Let the pigs find truffles at the Pig Farm."],["Clever noses","Truffles, deep in the soil."]]},{"stat":"made_honey","targets":[8,');
 pools:=replace(pools,'ts":[3,7,10],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[2,3,6],"titles":[["Preserve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[6,10,1','ts":[3,7,10],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[2,3,5],"titles":[["Preserve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[6,10,1');
 pools:=replace(pools,'[2,3,6],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","targets":[3,7,10],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[2,3,5],"t','[2,3,6],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","targets":[3,6,9],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[2,3,5],"t');
 pools:=replace(pools,'5,7],"titles":[["Stew pot","Slow-cooked stew from the Farm Kitchen."],["Supper time","Hearty bowls for hungry farmers."]]},{"stat":"made_applejuice","targets":[2,3,6],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","target','5,7],"titles":[["Stew pot","Slow-cooked stew from the Farm Kitchen."],["Supper time","Hearty bowls for hungry farmers."]]},{"stat":"made_applejuice","targets":[2,3,5],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","target');
 pools:=replace(pools,'0],"titles":[["Orchard salad","Fruit and greens from the Packing Shed."],["Fresh from the trees","A colourful salad from the orchard."]]},{"stat":"made_truffleomelette","targets":[2,5,7],"titles":[["Truffle breakfast","Truffles and eggs into a fine omelette."],["Chef’s special","The Farm Kitchen’s finest breakfast."]]},{"stat":"made_berrycheesecake","targets":[1,2,','0],"titles":[["Orchard salad","Fruit and greens from the Packing Shed."],["Fresh from the trees","A colourful salad from the orchard."]]},{"stat":"made_truffleomelette","targets":[2,4,6],"titles":[["Truffle breakfast","Truffles and eggs into a fine omelette."],["Chef’s special","The Farm Kitchen’s finest breakfast."]]},{"stat":"made_berrycheesecake","targets":[1,2,');
 pools:=replace(pools,'es and flour into warm apple pie."],["Pie in the oven","The smell of apple pie across the valley."]]},{"stat":"made_berrysmoothie","targets":[2,5,7],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[2,3,6],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,2,3],"titles":[["Bean jars","Green beans into pickled beans."],["Snap and crunch","Pickled beans for the shelves."]]},{"stat":"made_orchardsalad","targets":[3,7,1','es and flour into warm apple pie."],["Pie in the oven","The smell of apple pie across the valley."]]},{"stat":"made_berrysmoothie","targets":[2,5,7],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[2,3,5],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,2,3],"titles":[["Bean jars","Green beans into pickled beans."],["Snap and crunch","Pickled beans for the shelves."]]},{"stat":"made_orchardsalad","targets":[3,7,1');
 pools:=replace(pools,'"titles":[["Apple pie day","Apples and flour into warm apple pie."],["Pie in the oven","The smell of apple pie across the valley."]]},{"stat":"made_berrysmoothie","targets":[2,5,7],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[2,3,5],','"titles":[["Apple pie day","Apples and flour into warm apple pie."],["Pie in the oven","The smell of apple pie across the valley."]]},{"stat":"made_berrysmoothie","targets":[2,4,6],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[2,3,5],');
 pools:=replace(pools,'etables","targets":[3,5,8],"titles":[["Veggie','etables","targets":[1,2,3],"titles":[["Veggie');
 pools:=replace(pools,'r","targets":[8,13,20],"titles":[["','r","targets":[5,8,13],"titles":[["');
 pools:=replace(pools,'d","targets":[4,6,10],"titles":[["','d","targets":[3,4,6],"titles":[["');
 pools:=replace(pools,',4,5],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,5,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm',',4,5],"titles":[["Helping hands","Lend a hand around the farm."],["Odd jobs","The little jobs that keep a farm running."]]},{"stat":"activities","targets":[3,4,8],"titles":[["A helping hand","Help at the greenhouse, the apiary, the paddock and the workshop."],["Around the farm","Lend a hand at every stop on the farm');
 pools:=replace(pools,'1400,2200],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,20,40],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","targets":','1400,2200],"titles":[["Big spenders","Seeds, upgrades and new buildings: invest in your farm."],["Shopping spree","Put your coins to work on the farm."]]},{"stat":"diamonds_spent","targets":[10,10,20],"titles":[["Diamond day","Spend diamonds on boosts or on finishing fields and batches."],["Sparkle and shine","Let your diamonds do some of the work today."]]},{"stat":"sold_wheat","targets":');
 pools:=replace(pools,' farmers."]]},{"stat":"made_applejuice","targets":[2,3,5],"titles":[["Pressing day","Apples into juice at the Juice Press."],["Sweet and fresh","Bottle after bottle of apple juice."]]},{"stat":"made_orchardjuice","targets":[3,6,9],"titles":[["Orchard blend","The orchard’s best, pressed and bottled."],["Juice bar","Keep the Juice Press busy all day."]]},{"stat":"made_berrypreserves","targets":[2,3,5],"titles":[["Preserve the summer","Berries into jars at the Preserves Workshop."],["Jars on the shelf","Sweet preserves for the winter."]]},{"stat":"made_truffles","targets":[6,10,14],"titles":[["Truffle hunt","Let the pigs find truffles at the Pig Farm."],["Clever noses","Truffles, deep in the soil."]]}],[',' farmers."]]}],[');
 pools:=replace(pools,'ful salad from the orchard."]]},{"stat":"made_truffleomelette","targets":[2,4,6],"titles":[["Truffle breakfast","Truffles and eggs into a fine omelette."],["Chef’s special","The Farm Kitchen’s finest breakfast."]]},{"stat":"made_pie","','ful salad from the orchard."]]},{"stat":"made_pie","');
 pools:=replace(pools,'s the valley."]]},{"stat":"made_berrysmoothie","targets":[2,4,6],"titles":[["Smoothie stand","Berries into smoothies at the Juice Press."],["Berry blend","A cold smoothie for every farmer."]]},{"stat":"made_applecompote","targets":[2,3,5],"titles":[["Compote pot","Honey and apples into sweet compote."],["Sweet apples","Jars of honey apple compote."]]},{"stat":"made_pickledbeans","targets":[1,2,3],"titles":[["Bean jars","Green beans into pickled beans."],["Snap and crunch","Pickled beans for the shelves."]]},{"stat":"made_orchardsalad","targets":[3,6,9],','s the valley."]]},{"stat":"made_orchardsalad","targets":[3,6,9],');
 pools:=replace(pools,'etables","targets":[2,5,7],"titles":[["Veggie','etables","targets":[1,2,3],"titles":[["Veggie');
 pools:=replace(pools,'r","targets":[7,12,17],"titles":[["','r","targets":[5,7,12],"titles":[["');
 pools:=replace(pools,'tilized","targets":[3,6,9],"titles":[["Rich s','tilized","targets":[2,3,6],"titles":[["Rich s');
 pools:=replace(pools,'ities","targets":[3,5,8],"titles":[["A he','ities","targets":[3,4,8],"titles":[["A he');
 pools:=replace(pools,'ts":[10,20,40],"titl','ts":[10,10,20],"titl');
 pools:=replace(pools,'":"made_vegetables","targets":[2,4,6],"titles":[["Veggie boxes","Pack your vegetables for a better price."],["Box it up","Crate after crate from the Packing Shed."]]},{"stat":"made_fertiliz','":"made_fertiliz');
 pools:=replace(pools,'r","targets":[6,10,15],"titles":[["','r","targets":[4,6,10],"titles":[["');
 pools:=replace(pools,',18],"titles":[["Tender care","A little care makes every harvest bigger."],["Walk the rows","Look after every crop, row by row."]]},{"stat":"fertilized","targets":[3,5,8],"titles":[["Rich soil","Fertilize your fields for a faster harvest."],["Growing strong","A little fertilizer, a lot of growth."]]}],[{"stat":"harvest_wheat","targ',',18],"titles":[["Tender care","A little care makes every harvest bigger."],["Walk the rows","Look after every crop, row by row."]]},{"stat":"fertilized","targets":[2,3,5],"titles":[["Rich soil","Fertilize your fields for a faster harvest."],["Growing strong","A little fertilizer, a lot of growth."]]}],[{"stat":"harvest_wheat","targ');
 if md5(pools)<>'badc8ae11b1bba4dcaf6b69cc21f5f62' then raise exception using message='the new goals do not come out as public/event-goals.js has them'; end if;
 execute overlay(def placing pools from a for b-1);
end $do$;
