// The sign-up confirmation and password reset emails, in every game language (29 Sep 2026; moved here 30 Sep 2026). One source for
// the Supabase templates (scripts/email-templates.mjs) and the Send Email Hook (index.ts, mail.js).
const NB='\u00a0';
export const COPY={
 en:'Button not working? Copy this link into your browser:',nl:'Werkt de knop niet? Kopieer deze link naar je browser:',
 de:'Der Button funktioniert nicht? Kopiere diesen Link in deinen Browser:',es:'¿El botón no funciona? Copia este enlace en tu navegador:',
 fr:`Le bouton ne marche pas${NB}? Copie ce lien dans ton navigateur${NB}:`,pt:'O botão não funciona? Copie este link no seu navegador:',
 id:'Tombol tidak berfungsi? Salin tautan ini ke browsermu:',tr:'Düğme çalışmıyor mu? Bu bağlantıyı tarayıcına kopyala:',
 hu:'Nem működik a gomb? Másold be ezt a linket a böngésződbe:',ru:'Кнопка не работает? Скопируй эту ссылку в браузер:',
 uk:'Кнопка не працює? Скопіюй це посилання в браузер:',cs:'Tlačítko nefunguje? Zkopíruj tento odkaz do prohlížeče:',
 hi:'बटन काम नहीं कर रहा? यह लिंक अपने ब्राउज़र में कॉपी करें:',ja:'ボタンが使えない場合は、このリンクをブラウザにコピーしてください：',
 ar:'الزر لا يعمل؟ انسخ هذا الرابط إلى متصفحك:',zh:'按钮无法使用？请把这个链接复制到浏览器中：'
};
export const TAG={
 en:'A little farm. A world of possibilities.',nl:'Een kleine boerderij. Een wereld aan mogelijkheden.',de:'Ein kleiner Hof. Eine Welt voller Möglichkeiten.',
 es:'Una pequeña granja. Un mundo de posibilidades.',fr:'Une petite ferme. Un monde de possibilités.',pt:'Uma pequena fazenda. Um mundo de possibilidades.',
 id:'Kebun kecil. Dunia penuh kemungkinan.',tr:'Küçük bir çiftlik. Olasılıklarla dolu bir dünya.',hu:'Egy kis farm. Egy világnyi lehetőség.',
 ru:'Маленькая ферма. Целый мир возможностей.',uk:'Маленька ферма. Цілий світ можливостей.',cs:'Malá farma. Svět plný možností.',
 hi:'एक छोटा फ़ार्म। संभावनाओं की पूरी दुनिया।',ja:'小さな農場。可能性に満ちた世界。',
 ar:'مزرعة صغيرة. عالم من الإمكانيات.',zh:'一座小农场，一个充满可能的世界。'
};
export const TEMPLATES={
 'confirm-signup':{
  en:{title:'Welcome to the valley!',pre:'One tap and your farm is ready.',intro:'Thanks for signing up. Confirm your email address and your farm opens right away: a patch of land, a few seeds and a first harvest waiting for you.',button:'Confirm and start my farm',foot:'You received this email because someone signed up for Harvest Tycoon with this address. If that was not you, you can safely ignore it.'},
  nl:{title:'Welkom in de vallei!',pre:'Eén tik en je boerderij staat klaar.',intro:'Bedankt voor je aanmelding. Bevestig je e-mailadres en je boerderij gaat meteen open: een lapje grond, een paar zaadjes en een eerste oogst die op je wacht.',button:'Bevestig en start mijn boerderij',foot:'Je krijgt deze e-mail omdat iemand zich met dit adres heeft aangemeld bij Harvest Tycoon. Was jij dat niet? Dan kun je deze e-mail gerust negeren.'},
  de:{title:'Willkommen im Tal!',pre:'Ein Tipp, und dein Hof ist bereit.',intro:'Danke für deine Anmeldung. Bestätige deine E-Mail-Adresse, und dein Hof öffnet sich sofort: ein Stück Land, ein paar Samen und eine erste Ernte, die auf dich wartet.',button:'Bestätigen und meinen Hof starten',foot:'Du bekommst diese E-Mail, weil sich jemand mit dieser Adresse bei Harvest Tycoon angemeldet hat. Warst du das nicht, kannst du sie einfach ignorieren.'},
  es:{title:'¡Te damos la bienvenida al valle!',pre:'Un toque y tu granja está lista.',intro:'Gracias por registrarte. Confirma tu correo y tu granja se abre al instante: un trozo de tierra, unas semillas y una primera cosecha esperándote.',button:'Confirmar y empezar mi granja',foot:'Recibes este correo porque alguien se registró en Harvest Tycoon con esta dirección. Si no fuiste tú, puedes ignorarlo sin problema.'},
  fr:{title:`Bienvenue dans la vallée${NB}!`,pre:'Un geste et ta ferme est prête.',intro:`Merci pour ton inscription. Confirme ton adresse e-mail et ta ferme s’ouvre aussitôt${NB}: un lopin de terre, quelques graines et une première récolte qui t’attend.`,button:'Confirmer et lancer ma ferme',foot:'Tu reçois cet e-mail parce que quelqu’un s’est inscrit à Harvest Tycoon avec cette adresse. Si ce n’était pas toi, tu peux l’ignorer sans souci.'},
  pt:{title:'Boas-vindas ao vale!',pre:'Um toque e sua fazenda está pronta.',intro:'Obrigado por se cadastrar. Confirme seu e-mail e sua fazenda abre na hora: um pedaço de terra, algumas sementes e uma primeira colheita esperando por você.',button:'Confirmar e começar minha fazenda',foot:'Você recebeu este e-mail porque alguém se cadastrou no Harvest Tycoon com este endereço. Se não foi você, pode ignorá-lo tranquilamente.'},
  id:{title:'Selamat datang di lembah!',pre:'Sekali ketuk, kebunmu siap.',intro:'Terima kasih sudah mendaftar. Konfirmasi alamat emailmu dan kebunmu langsung terbuka: sepetak tanah, beberapa benih, dan panen pertama yang menunggumu.',button:'Konfirmasi dan mulai kebunku',foot:'Kamu menerima email ini karena seseorang mendaftar di Harvest Tycoon dengan alamat ini. Jika itu bukan kamu, abaikan saja.'},
  tr:{title:'Vadiye hoş geldin!',pre:'Tek dokunuşla çiftliğin hazır.',intro:'Kaydolduğun için teşekkürler. E-posta adresini onayla, çiftliğin hemen açılsın: bir parça toprak, birkaç tohum ve seni bekleyen ilk hasat.',button:'Onayla ve çiftliğimi başlat',foot:'Bu e-postayı, biri bu adresle Harvest Tycoon’a kaydolduğu için alıyorsun. Bu sen değilsen, gönül rahatlığıyla görmezden gelebilirsin.'},
  hu:{title:'Üdv a völgyben!',pre:'Egy koppintás, és kész a farmod.',intro:'Köszönjük, hogy regisztráltál. Erősítsd meg az e-mail-címed, és a farmod azonnal megnyílik: egy darab föld, néhány mag és egy első termés vár rád.',button:'Megerősítés és a farmom indítása',foot:'Azért kapod ezt az e-mailt, mert valaki ezzel a címmel regisztrált a Harvest Tycoonba. Ha nem te voltál, nyugodtan hagyd figyelmen kívül.'},
  ru:{title:'Добро пожаловать в долину!',pre:'Одно касание, и ферма готова.',intro:'Спасибо за регистрацию. Подтверди адрес почты, и ферма сразу откроется: клочок земли, немного семян и первый урожай уже ждут тебя.',button:'Подтвердить и начать',foot:'Это письмо пришло, потому что кто-то зарегистрировался в Harvest Tycoon с этим адресом. Если это был не ты, просто не обращай на него внимания.'},
  uk:{title:'Ласкаво просимо до долини!',pre:'Один дотик, і ферма готова.',intro:'Дякуємо за реєстрацію. Підтверди адресу пошти, і ферма одразу відкриється: клапоть землі, трохи насіння й перший урожай уже чекають на тебе.',button:'Підтвердити й почати',foot:'Цей лист надійшов, бо хтось зареєструвався в Harvest Tycoon з цією адресою. Якщо це був не ти, просто не зважай на нього.'},
  cs:{title:'Vítej v údolí!',pre:'Jedno klepnutí a farma je připravená.',intro:'Díky za registraci. Potvrď svou e-mailovou adresu a farma se hned otevře: kousek půdy, pár semínek a první sklizeň, která na tebe čeká.',button:'Potvrdit a spustit moji farmu',foot:'Tento e-mail ti přišel, protože se někdo s touto adresou zaregistroval do Harvest Tycoon. Pokud to nebyl tvůj požadavek, můžeš ho klidně ignorovat.'},
  hi:{title:'घाटी में आपका स्वागत है!',pre:'एक टैप और आपका फ़ार्म तैयार।',intro:'साइन अप करने के लिए धन्यवाद। अपना ईमेल पता पक्का करें और आपका फ़ार्म तुरंत खुल जाएगा: ज़मीन का एक टुकड़ा, कुछ बीज और पहली फसल आपका इंतज़ार कर रही है।',button:'पक्का करें और मेरा फ़ार्म शुरू करें',foot:'आपको यह ईमेल इसलिए मिला है क्योंकि किसी ने इस पते से Harvest Tycoon पर साइन अप किया है। अगर वह आप नहीं थे, तो इसे आराम से अनदेखा कर दें।'},
  ja:{title:'谷へようこそ！',pre:'タップひとつで農場の準備ができます。',intro:'ご登録ありがとうございます。メールアドレスを確認すると、すぐに農場が開きます。小さな土地と少しの種、そして最初の収穫があなたを待っています。',button:'確認して農場を始める',foot:'このアドレスでHarvest Tycoonに登録があったため、このメールをお送りしています。心当たりがない場合は、このメールを無視してください。'},
  ar:{title:'مرحبًا بك في الوادي!',pre:'لمسة واحدة ومزرعتك جاهزة.',intro:'شكرًا لتسجيلك. أكّد عنوان بريدك الإلكتروني وستُفتح مزرعتك على الفور: قطعة أرض وبعض البذور وأول حصاد بانتظارك.',button:'أكّد وابدأ مزرعتي',foot:'وصلتك هذه الرسالة لأن شخصًا ما سجّل في Harvest Tycoon بهذا العنوان. إن لم تكن أنت، يمكنك تجاهلها بأمان.'},
  zh:{title:'欢迎来到山谷！',pre:'轻点一下，你的农场就准备好了。',intro:'感谢注册。验证你的邮箱地址后，你的农场会立即开放：一小块土地、几颗种子，还有第一次收获在等着你。',button:'验证并开始我的农场',foot:'你收到这封邮件，是因为有人用这个地址注册了 Harvest Tycoon。如果不是你本人，可以放心忽略。'}
 },
 'reset-password':{
  en:{title:'Choose a new password',pre:'Choose a new password for your farm.',intro:'We received a request to reset the password for your Harvest Tycoon account. Tap the button to choose a new one. Your farm and progress stay exactly as you left them.',button:'Choose a new password',foot:'If you did not ask for this, ignore this email: your password stays the same. The link works once and expires after a while.'},
  nl:{title:'Kies een nieuw wachtwoord',pre:'Kies een nieuw wachtwoord voor je boerderij.',intro:'We kregen een verzoek om het wachtwoord van je Harvest Tycoon-account opnieuw in te stellen. Tik op de knop om een nieuw wachtwoord te kiezen. Je boerderij en voortgang blijven precies zoals je ze achterliet.',button:'Kies een nieuw wachtwoord',foot:'Heb je hier niet om gevraagd? Negeer deze e-mail dan: je wachtwoord blijft hetzelfde. De link werkt één keer en verloopt na een tijdje.'},
  de:{title:'Wähle ein neues Passwort',pre:'Wähle ein neues Passwort für deinen Hof.',intro:'Wir haben eine Anfrage erhalten, das Passwort deines Harvest-Tycoon-Kontos zurückzusetzen. Tippe auf den Button, um ein neues zu wählen. Dein Hof und dein Fortschritt bleiben genau so, wie du sie verlassen hast.',button:'Neues Passwort wählen',foot:'Wenn du das nicht angefordert hast, ignoriere diese E-Mail: Dein Passwort bleibt gleich. Der Link funktioniert einmal und läuft nach einer Weile ab.'},
  es:{title:'Elige una contraseña nueva',pre:'Elige una contraseña nueva para tu granja.',intro:'Recibimos una solicitud para restablecer la contraseña de tu cuenta de Harvest Tycoon. Toca el botón para elegir una nueva. Tu granja y tu progreso se quedan tal como los dejaste.',button:'Elegir una contraseña nueva',foot:'Si no lo pediste, ignora este correo: tu contraseña no cambia. El enlace funciona una vez y caduca al cabo de un rato.'},
  fr:{title:'Choisis un nouveau mot de passe',pre:'Choisis un nouveau mot de passe pour ta ferme.',intro:'Nous avons reçu une demande de réinitialisation du mot de passe de ton compte Harvest Tycoon. Touche le bouton pour en choisir un nouveau. Ta ferme et ta progression restent exactement comme tu les as laissées.',button:'Choisir un nouveau mot de passe',foot:`Si tu n’as rien demandé, ignore cet e-mail${NB}: ton mot de passe ne change pas. Le lien fonctionne une fois et expire au bout d’un moment.`},
  pt:{title:'Escolha uma nova senha',pre:'Escolha uma nova senha para sua fazenda.',intro:'Recebemos um pedido para redefinir a senha da sua conta do Harvest Tycoon. Toque no botão para escolher uma nova. Sua fazenda e seu progresso continuam exatamente como você deixou.',button:'Escolher uma nova senha',foot:'Se você não pediu isso, ignore este e-mail: sua senha continua a mesma. O link funciona uma vez e expira depois de um tempo.'},
  id:{title:'Pilih kata sandi baru',pre:'Pilih kata sandi baru untuk kebunmu.',intro:'Kami menerima permintaan untuk mengatur ulang kata sandi akun Harvest Tycoon-mu. Ketuk tombol untuk memilih yang baru. Kebun dan progresmu tetap seperti saat kamu tinggalkan.',button:'Pilih kata sandi baru',foot:'Jika kamu tidak memintanya, abaikan email ini: kata sandimu tetap sama. Tautan ini hanya berlaku sekali dan kedaluwarsa setelah beberapa waktu.'},
  tr:{title:'Yeni bir şifre seç',pre:'Çiftliğin için yeni bir şifre seç.',intro:'Harvest Tycoon hesabının şifresini sıfırlama isteği aldık. Yenisini seçmek için düğmeye dokun. Çiftliğin ve ilerlemen bıraktığın gibi kalır.',button:'Yeni şifre seç',foot:'Bunu sen istemediysen bu e-postayı görmezden gel: şifren aynı kalır. Bağlantı bir kez çalışır ve bir süre sonra geçerliliğini yitirir.'},
  hu:{title:'Válassz új jelszót',pre:'Válassz új jelszót a farmodhoz.',intro:'Kérést kaptunk a Harvest Tycoon-fiókod jelszavának visszaállítására. Koppints a gombra, és válassz újat. A farmod és a haladásod pontosan úgy marad, ahogy hagytad.',button:'Új jelszó választása',foot:'Ha nem te kérted, hagyd figyelmen kívül ezt az e-mailt: a jelszavad nem változik. A link egyszer használható, és egy idő után lejár.'},
  ru:{title:'Выбери новый пароль',pre:'Выбери новый пароль для своей фермы.',intro:'Мы получили запрос на сброс пароля для твоего аккаунта Harvest Tycoon. Нажми на кнопку, чтобы выбрать новый. Ферма и весь прогресс останутся в точности как были.',button:'Выбрать новый пароль',foot:'Если это был не ты, просто не обращай внимания на это письмо: пароль останется прежним. Ссылка работает один раз и через некоторое время перестаёт действовать.'},
  uk:{title:'Обери новий пароль',pre:'Обери новий пароль для своєї ферми.',intro:'Ми отримали запит на скидання пароля до твого облікового запису Harvest Tycoon. Натисни кнопку, щоб обрати новий. Ферма й увесь прогрес залишаться такими, як були.',button:'Обрати новий пароль',foot:'Якщо це був не ти, просто не зважай на цей лист: пароль не зміниться. Посилання працює один раз і згодом перестає діяти.'},
  cs:{title:'Zvol si nové heslo',pre:'Zvol si nové heslo ke své farmě.',intro:'Dostali jsme žádost o obnovení hesla k tvému účtu Harvest Tycoon. Klepni na tlačítko a zvol si nové. Tvoje farma i postup zůstanou beze změny.',button:'Zvolit nové heslo',foot:'Pokud to nebyl tvůj požadavek, tento e-mail ignoruj: heslo zůstane stejné. Odkaz funguje jednou a po čase vyprší.'},
  hi:{title:'नया पासवर्ड चुनें',pre:'अपने फ़ार्म के लिए नया पासवर्ड चुनें।',intro:'हमें आपके Harvest Tycoon खाते का पासवर्ड रीसेट करने का अनुरोध मिला है। नया पासवर्ड चुनने के लिए बटन दबाएँ। आपका फ़ार्म और आपकी प्रगति बिल्कुल वैसी ही रहेगी जैसी आपने छोड़ी थी।',button:'नया पासवर्ड चुनें',foot:'अगर आपने यह नहीं माँगा था, तो इस ईमेल को अनदेखा करें: आपका पासवर्ड वही रहेगा। लिंक एक बार काम करता है और कुछ समय बाद खत्म हो जाता है।'},
  ja:{title:'新しいパスワードを設定',pre:'農場の新しいパスワードを設定してください。',intro:'Harvest Tycoonアカウントのパスワード再設定のリクエストを受け付けました。ボタンをタップして新しいパスワードを設定してください。農場と進行状況はそのまま残ります。',button:'新しいパスワードを設定',foot:'心当たりがない場合は、このメールを無視してください。パスワードは変わりません。リンクは1回だけ有効で、しばらくすると期限切れになります。'},
  ar:{title:'اختر كلمة مرور جديدة',pre:'اختر كلمة مرور جديدة لمزرعتك.',intro:'وصلنا طلب لإعادة تعيين كلمة مرور حسابك في Harvest Tycoon. اضغط على الزر لاختيار كلمة جديدة. ستبقى مزرعتك وتقدّمك كما تركتهما تمامًا.',button:'اختر كلمة مرور جديدة',foot:'إن لم تطلب ذلك، تجاهل هذه الرسالة: ستبقى كلمة مرورك كما هي. يعمل الرابط مرة واحدة وتنتهي صلاحيته بعد فترة.'},
  zh:{title:'设置新密码',pre:'为你的农场设置一个新密码。',intro:'我们收到了重置你的 Harvest Tycoon 账号密码的请求。点击按钮设置新密码。你的农场和进度会保持原样。',button:'设置新密码',foot:'如果这不是你的请求，请忽略此邮件：你的密码不会改变。该链接只能使用一次，并会在一段时间后失效。'}
 }
};
// A subject per language (30 Sep 2026): the hook (index.ts) has no length limit, unlike a Supabase template's subject field.
export const SUBJECTS=Object.freeze({
 'confirm-signup':{en:'Confirm your email and start your farm',nl:'Bevestig je e-mail en start je boerderij',de:'Bestätige deine E-Mail und starte deinen Hof',
  es:'Confirma tu correo y empieza tu granja',fr:'Confirme ton e-mail et lance ta ferme',pt:'Confirme seu e-mail e comece sua fazenda',
  id:'Konfirmasi emailmu dan mulai kebunmu',tr:'E-postanı onayla ve çiftliğini başlat',hu:'Erősítsd meg az e-mail-címed, és indítsd a farmod',
  ru:'Подтверди почту и начни свою ферму',uk:'Підтверди пошту й почни свою ферму',cs:'Potvrď e-mail a spusť svou farmu',
  hi:'अपना ईमेल पक्का करें और अपना फ़ार्म शुरू करें',ja:'メールを確認して農場を始めましょう',ar:'أكّد بريدك الإلكتروني وابدأ مزرعتك',zh:'验证你的邮箱并开始你的农场'},
 'reset-password':{en:'Choose a new password for Harvest Tycoon',nl:'Kies een nieuw wachtwoord voor Harvest Tycoon',de:'Wähle ein neues Passwort für Harvest Tycoon',
  es:'Elige una contraseña nueva para Harvest Tycoon',fr:'Choisis un nouveau mot de passe pour Harvest Tycoon',pt:'Escolha uma nova senha para o Harvest Tycoon',
  id:'Pilih kata sandi baru untuk Harvest Tycoon',tr:'Harvest Tycoon için yeni bir şifre seç',hu:'Válassz új jelszót a Harvest Tycoonhoz',
  ru:'Выбери новый пароль для Harvest Tycoon',uk:'Обери новий пароль для Harvest Tycoon',cs:'Zvol si nové heslo pro Harvest Tycoon',
  hi:'Harvest Tycoon के लिए नया पासवर्ड चुनें',ja:'Harvest Tycoonの新しいパスワードを設定',ar:'اختر كلمة مرور جديدة لـ Harvest Tycoon',zh:'为 Harvest Tycoon 设置新密码'}
});
// The emoji in front of each subject, as in the Supabase templates' subjects.
export const SUBJECT_ICONS=Object.freeze({'confirm-signup':'🌱','reset-password':'🔑'});
// Languages that read from right to left: their emails run right to left (dir="rtl").
export const RTL=Object.freeze(['ar']);
