import {copyFileSync,readFileSync,writeFileSync} from 'node:fs';
for(const name of ['diamond-checkout','stripe-webhook','play-voided','app-store-notify'])copyFileSync(new URL('../game/payments.js',import.meta.url),new URL(`../supabase/functions/${name}/payments.js`,import.meta.url));
// Google Play's server API (Oct 2026): checking and consuming the Android app's purchases, and its refunds.
for(const name of ['diamond-checkout','play-voided'])copyFileSync(new URL('../game/google-play.js',import.meta.url),new URL(`../supabase/functions/${name}/google-play.js`,import.meta.url));
// The App Store (Oct 2026): Apple's signed purchases, checked without a key, for the iPhone app's purchases and Apple's notifications.
for(const name of ['diamond-checkout','app-store-notify'])copyFileSync(new URL('../game/app-store.js',import.meta.url),new URL(`../supabase/functions/${name}/app-store.js`,import.meta.url));
copyFileSync(new URL('../game/farm-state.js',import.meta.url),new URL('../public/farm-state.js',import.meta.url));

copyFileSync(new URL('../game/farm-state.js',import.meta.url),new URL('../supabase/functions/farm-api/farm-state.js',import.meta.url));

copyFileSync(new URL('../src/presence.js',import.meta.url),new URL('../supabase/functions/farm-api/presence.js',import.meta.url));

// The friendly default name ("Sunny Acres 4821") for a farmer who signed in with Facebook or Google and brought none.
copyFileSync(new URL('../src/account-form.js',import.meta.url),new URL('../supabase/functions/farm-api/account-form.js',import.meta.url));
// The same name maker and "Name 2" rule for a CrazyGames username (crazygames-auth, Oct 2026).
copyFileSync(new URL('../src/account-form.js',import.meta.url),new URL('../supabase/functions/crazygames-auth/account-form.js',import.meta.url));
// And for a Kongregate username (kongregate-auth, Oct 2026).
copyFileSync(new URL('../src/account-form.js',import.meta.url),new URL('../supabase/functions/kongregate-auth/account-form.js',import.meta.url));
// And for a new Discord farm's random name (discord-auth, Oct 2026).
copyFileSync(new URL('../src/account-form.js',import.meta.url),new URL('../supabase/functions/discord-auth/account-form.js',import.meta.url));

copyFileSync(new URL('../public/player-avatars.js',import.meta.url),new URL('../supabase/functions/farm-api/player-avatars.js',import.meta.url));

// The reminder job only needs the display names of crops and buildings, not the whole game.
{
 const {CROPS,BUILDINGS}=await import('../game/farm-state.js');
 const names=map=>JSON.stringify(Object.fromEntries(Object.entries(map).map(([key,value])=>[key,value.name])));
 // The same names in every game language (public/i18n/<code>.json), for reminders in the farmer's own language. A name that is not
 // translated yet is left out, so it stays English.
 const {LANGUAGES}=await import('../public/languages.js');
 const local={};
 for(const {code} of LANGUAGES.filter(l=>l.code!=='en')){
  let texts={};try{texts=JSON.parse(readFileSync(new URL(`../public/i18n/${code}.json`,import.meta.url),'utf8'));}catch{}
  const pick=map=>Object.fromEntries(Object.entries(map).filter(([,value])=>typeof texts[value.name]==='string').map(([key,value])=>[key,texts[value.name]]));
  local[code]={crops:pick(CROPS),buildings:pick(BUILDINGS)};
 }
 writeFileSync(new URL('../supabase/functions/notify-hourly/names.js',import.meta.url),`// Generated by scripts/sync-game.mjs from game/farm-state.js and public/i18n. Do not edit by hand.\nexport const CROP_NAMES=${names(CROPS)};\nexport const BUILDING_NAMES=${names(BUILDINGS)};\nexport const LOCAL_NAMES=${JSON.stringify(local)};\n`);
}
