import {copyFileSync,writeFileSync} from 'node:fs';
for(const name of ['diamond-checkout','stripe-webhook'])copyFileSync(new URL('../game/payments.js',import.meta.url),new URL(`../supabase/functions/${name}/payments.js`,import.meta.url));
copyFileSync(new URL('../game/farm-state.js',import.meta.url),new URL('../public/farm-state.js',import.meta.url));

copyFileSync(new URL('../game/farm-state.js',import.meta.url),new URL('../supabase/functions/farm-api/farm-state.js',import.meta.url));

copyFileSync(new URL('../src/presence.js',import.meta.url),new URL('../supabase/functions/farm-api/presence.js',import.meta.url));

// The reminder job only needs the display names of crops and buildings, not the whole game.
{
 const {CROPS,BUILDINGS}=await import('../game/farm-state.js');
 const names=map=>JSON.stringify(Object.fromEntries(Object.entries(map).map(([key,value])=>[key,value.name])));
 writeFileSync(new URL('../supabase/functions/notify-hourly/names.js',import.meta.url),`// Generated by scripts/sync-game.mjs from game/farm-state.js. Do not edit by hand.\nexport const CROP_NAMES=${names(CROPS)};\nexport const BUILDING_NAMES=${names(BUILDINGS)};\n`);
}
