const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const local=t=>{const d=new Date(t);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const labels={harvested:'Harvest crops',produced:'Collect batches',watered:'Water fields',tended:'Care for fields',chores:'Complete chores',deliveries:'Complete deliveries'};
export function mountAdminEvents(root,bridge){
 let events=[],selected=null,offset=0,resultEvent=null;
 root.innerHTML='<h3><img src="/assets/icons/live-events.png" alt="" width="36" height="36"> Short live events</h3><p>Schedule 1–12 hour events. Started rules are frozen; activation can be paused. All times below use your local timezone.</p><button class="small-button" data-new>New event</button><button class="small-button" data-refresh>Refresh events</button><div data-list></div><div data-editor></div><div data-results></div><p role="status" data-status></p>';
 const status=root.querySelector('[data-status]');
 const request=data=>bridge.request({operation:'admin_events',...data});
 async function execute(task){try{status.textContent='Working…';await task();status.textContent='Up to date.';}catch(e){status.textContent=e.message;}}
 async function load(){const data=await request({command:'list'});events=data.events;root.querySelector('[data-list]').innerHTML=events.map(e=>`<article class="admin-card"><strong>${esc(e.title)}</strong><p>${new Date(e.starts_at).toLocaleString('en-US')} – ${new Date(e.ends_at).toLocaleString('en-US')} · ${e.settled_at?'Settled':Date.parse(e.ends_at)<=Date.now()?'Ended':!e.active?'Inactive':Date.parse(e.starts_at)>Date.now()?'Scheduled':'Live'} · ${e.participants} participants</p><button class="small-button" data-edit="${e.id}" ${Date.parse(e.starts_at)<=Date.now()?'disabled':''}>Edit</button><button class="small-button" data-toggle="${e.id}" ${e.settled_at||Date.parse(e.ends_at)<=Date.now()?'disabled':''}>${e.active?'Deactivate':'Activate'}</button><button class="small-button" data-results-id="${e.id}">Participation &amp; rewards</button></article>`).join('')||'<p>No events configured.</p>';
 root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editor(events.find(e=>e.id===b.dataset.edit)));
 root.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>execute(async()=>{const e=events.find(e=>e.id===b.dataset.toggle);await request({command:'toggle',eventId:e.id,active:!e.active});await load();}));
 root.querySelectorAll('[data-results-id]').forEach(b=>b.onclick=()=>{offset=0;resultEvent=b.dataset.resultsId;execute(results);});}
 function editor(e){selected=e?.id??null;const values=e??{title:'Harvest hour',description:'Bring in the harvest together!',starts_at:new Date(Date.now()+3600000).toISOString(),ends_at:new Date(Date.now()+3*3600000).toISOString(),objectives:[{stat:'harvested',target:30},{stat:'watered',target:10}],rewards:{coins:60,diamondMin:1,diamondMax:3,participantStep:25,poolCap:100}};
 root.querySelector('[data-editor]').innerHTML=`<form class="admin-card"><h3>${e?'Edit event':'New event'}</h3><label>Title <input name="title" required minlength="3" maxlength="80" value="${esc(values.title)}"></label><label>Description <textarea name="description" maxlength="500">${esc(values.description)}</textarea></label><label>Starts <input type="datetime-local" name="starts_at" value="${local(values.starts_at)}" required></label><label>Ends <input type="datetime-local" name="ends_at" value="${local(values.ends_at)}" required></label><fieldset><legend>Objectives (choose 1–4; blank = disabled)</legend>${Object.entries(labels).map(([key,label])=>`<label>${label} <input name="objective_${key}" type="number" min="1" max="10000" step="1" value="${values.objectives.find(o=>o.stat===key)?.target??''}"></label>`).join('')}</fieldset><fieldset><legend>Rewards per qualified player</legend>${[['coins','Coins',0,300],['diamondMin','Base diamonds',0,1],['diamondMax','Maximum diamonds',1,3],['participantStep','Qualified participants per growth step',10,1000],['poolCap','Maximum event diamond pool',0,200]].map(([k,label,min,max])=>`<label>${label} <input name="${k}" type="number" min="${min}" max="${max}" step="1" value="${values.rewards[k]}" required></label>`).join('')}</fieldset><p>Diamonds = min(maximum, base + floor(sqrt(qualified participants / growth step))). The total pool is capped. Earlier completions receive diamonds first if the pool runs out. Each player can collect at most 6 event diamonds per UTC day; excess is forfeited.</p><p>Qualification: verified account aged 48 hours, level 10, all objectives and at least 3 contributing actions over 10 minutes. Progress updates at most once per 10 seconds.</p><label><input name="active" type="checkbox" ${values.active?'checked':''}> Active</label><button class="primary-button">Save event</button></form>`;
 root.querySelector('form').onsubmit=ev=>{ev.preventDefault();const form=ev.target,data=Object.fromEntries(new FormData(form));execute(async()=>{await request({command:'save',eventId:selected,config:{title:data.title,description:data.description,starts_at:new Date(data.starts_at).toISOString(),ends_at:new Date(data.ends_at).toISOString(),active:data.active==='on',objectives:Object.keys(labels).filter(k=>data['objective_'+k]).map(stat=>({stat,target:Number(data['objective_'+stat])})),rewards:Object.fromEntries(['coins','diamondMin','diamondMax','participantStep','poolCap'].map(k=>[k,Number(data[k])]))}});root.querySelector('[data-editor]').innerHTML='';await load();});};}
 async function results(){const r=await request({command:'results',eventId:resultEvent,offset});root.querySelector('[data-results]').innerHTML=`<h3>${esc(r.event.title)} — participation &amp; distribution</h3><p>${r.total} participants · ${r.event.qualified} qualified · ${r.event.diamond_pool} diamonds allocated · ${r.event.settled_at?'Settled '+new Date(r.event.settled_at).toLocaleString('en-US'):'Results pending'}</p><div class="admin-table-scroll"><table class="admin-table"><thead><tr><th>Player ID</th><th>Progress</th><th>Actions</th><th>Qualified</th><th>Coins / diamonds</th><th>Paid diamonds</th><th>Claimed</th></tr></thead><tbody>${r.players.map(p=>`<tr><td>${esc(p.player_id)}</td><td>${esc(JSON.stringify(p.progress))}</td><td>${p.actions}</td><td>${p.qualified?'Yes':'No'}</td><td>${p.coins} / ${p.diamonds}</td><td>${p.paid_diamonds}</td><td>${p.claimed_at?esc(new Date(p.claimed_at).toLocaleString('en-US')):'Pending'}</td></tr>`).join('')}</tbody></table></div><button class="small-button" data-prev ${offset===0?'disabled':''}>Previous 100</button><button class="small-button" data-next ${offset+100>=r.total?'disabled':''}>Next 100</button>`;root.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-100);execute(results);};root.querySelector('[data-next]').onclick=()=>{offset+=100;execute(results);};}
 root.querySelector('[data-new]').onclick=()=>editor();root.querySelector('[data-refresh]').onclick=()=>execute(load);
 return {load:()=>execute(load)};
}
