const $=id=>document.getElementById(id);
export function createCloudUI({onOpen,onName,onRetry,onAccount}){
 const button=document.createElement('button');button.id='leaderboard-button';button.className='leaderboard-button';button.setAttribute('aria-haspopup','dialog');button.innerHTML='<i data-lucide="trophy"></i><span>Leaderboard</span>';
 document.querySelector('.tool-dock').append(button);
 const holder=document.createElement('div');holder.innerHTML=`<dialog id="leaderboard-dialog" class="game-dialog wide-dialog" aria-labelledby="leaderboard-title"><div class="dialog-heading"><div><span class="eyebrow">GROWING TOGETHER</span><h2 id="leaderboard-title">The valley leaderboard</h2></div><button class="icon-button" data-cloud-close aria-label="Close"><i data-lucide="x"></i></button></div><p class="leaderboard-intro">The top 20 farmers by current coins. Shared scores, personal farms.</p><div class="cloud-profile"><span id="player-name">Your farmer profile</span><button class="small-button" id="rename-player" hidden>Change name</button><button class="small-button" id="account-player" hidden>Keep my player ID</button></div><div class="cloud-sync"><span id="cloud-status" role="status">Connecting…</span><button id="retry-cloud" class="back-button">Refresh</button></div><div id="leaderboard-results" aria-live="polite"></div><p class="cloud-privacy">Only your display name, coins and level are shared. Your fields, inventory and buildings stay on this device.</p></dialog>
 <dialog id="username-dialog" class="game-dialog" aria-labelledby="username-title"><div class="dialog-heading"><div><span class="eyebrow">MEET THE OTHER FARMERS</span><h2 id="username-title">What should we call you?</h2></div><button class="icon-button" data-cloud-close aria-label="Keep playing"><i data-lucide="x"></i></button></div><p class="section-copy">Choose the display name other players will see on the leaderboard.</p><form id="username-form"><label for="username-input">Display name</label><input id="username-input" name="username" autocomplete="nickname" minlength="3" maxlength="20" required placeholder="Sunny Acres"><small>3–20 letters, numbers, spaces, underscores or hyphens.</small><p id="username-error" class="cloud-form-error" role="alert"></p><button class="primary-button" type="submit">Join the leaderboard<i data-lucide="arrow-right"></i></button><button class="back-button" type="button" data-cloud-close>Keep farming for now</button></form></dialog>
 <dialog id="account-dialog" class="game-dialog" aria-labelledby="account-title"><div class="dialog-heading"><div><span class="eyebrow">YOUR PLACE IN THE VALLEY</span><h2 id="account-title">Keep your player identity</h2></div><button class="icon-button" data-cloud-close aria-label="Close"><i data-lucide="x"></i></button></div><p class="section-copy">Link an email to use the same leaderboard identity on another device. Your farm itself stays in this browser; each device posts its own current score.</p><form id="account-form"><label for="account-mode">I want to</label><select id="account-mode"><option value="link">Link this anonymous player</option><option value="signin">Sign in to an existing player</option></select><label for="account-email">Email address</label><input id="account-email" name="email" type="email" autocomplete="email" required placeholder="you@example.com"><p id="account-message" class="cloud-form-error" role="status"></p><button class="primary-button" type="submit">Send email link<i data-lucide="mail"></i></button></form></dialog>`;
 document.body.append(...holder.children);
 function show(id){document.querySelectorAll('dialog[open]').forEach(d=>d.close());$(id).showModal();}
 function promptName(name=''){$('username-input').value=name;$('username-error').textContent='';show('username-dialog');$('username-input').focus();}
 document.querySelectorAll('[data-cloud-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 button.onclick=()=>{show('leaderboard-dialog');onOpen();};$('retry-cloud').onclick=onRetry;
 $('rename-player').onclick=()=>promptName($('player-name').dataset.username??'');
 $('account-player').onclick=()=>show('account-dialog');
 $('username-form').onsubmit=async event=>{event.preventDefault();const submit=event.currentTarget.querySelector('[type="submit"]');submit.disabled=true;$('username-error').textContent='';try{await onName($('username-input').value);show('leaderboard-dialog');await onOpen();}catch(error){$('username-error').textContent=error.message;}finally{submit.disabled=false;}};
 $('account-form').onsubmit=async event=>{event.preventDefault();const submit=event.currentTarget.querySelector('button');submit.disabled=true;$('account-message').textContent='Sending…';try{await onAccount($('account-email').value,$('account-mode').value);$('account-message').textContent='Check your inbox and open the confirmation link. You can keep farming while you wait.';}catch(error){$('account-message').textContent=error.message;}finally{submit.disabled=false;}};
 window.lucide?.createIcons();
 return {
  promptName,
  setProfile(profile,player){$('player-name').textContent=profile?profile.username:'Pick your farmer name';$('player-name').dataset.username=profile?.username??'';$('rename-player').hidden=!player;$('account-player').hidden=!player;$('account-player').textContent=player?.is_anonymous?'Keep my player ID':'Player account';},
  status(text){$('cloud-status').textContent=text;},
  message(text){const p=document.createElement('p');p.className='leaderboard-empty';p.textContent=text;$('leaderboard-results').replaceChildren(p);},
  get results(){return $('leaderboard-results');},
  get open(){return $('leaderboard-dialog').open;}
 };
}
