import {LEADERBOARD_CATEGORIES} from './leaderboard.js';
import {art} from '../public/visual-icons.js';
import {rankPickerMarkup,bindRankPicker,rankArtKey} from '../public/rank-picker.js';
import {playerAvatar} from '../public/player-avatars.js';
import {isRandomPlayerName} from './account-form.js';
const $=id=>document.getElementById(id);
export function createCloudUI({onOpen,onName,onRetry,onSignIn,onRegister,onSignOut,onPlayer}){
 // A side tool next to Invite (friends together); phones open it from the More menu.
 const button=document.createElement('button');button.id='leaderboard-button';button.className='side-tool';button.setAttribute('aria-haspopup','dialog');button.innerHTML='<span><i data-lucide="trophy"></i></span><b>Leaderboard</b>';const invite=document.getElementById('invite-button');if(invite)invite.after(button);else document.querySelector('.side-tools,.tool-dock')?.append(button);
 const holder=document.createElement('div');holder.innerHTML=`<dialog id="auth-dialog" class="game-dialog auth-dialog" aria-labelledby="auth-title" data-keep-open><div class="auth-brand"><img src="/assets/harvest-tycoon-logo.webp" alt="" width="92" height="92"><div><span class="eyebrow">WELCOME BACK TO THE FARM</span><h2 id="auth-title">Save your progress</h2></div></div><p class="section-copy">Sign in to access your coins, level, and player name on any device.</p><div class="auth-tabs" role="tablist"><button type="button" role="tab" data-auth-tab="signin" aria-selected="true">Sign in</button><button type="button" role="tab" data-auth-tab="register" aria-selected="false">Create account</button></div><form id="auth-form"><div id="register-name-row" hidden><label for="auth-username">Player name</label><input id="auth-username" autocomplete="nickname" minlength="3" maxlength="20" placeholder="Sunny Acres"></div><label for="auth-email">Email address</label><input id="auth-email" type="email" autocomplete="email" required placeholder="you@example.com"><label for="auth-password">Password</label><input id="auth-password" type="password" autocomplete="current-password" minlength="6" required><p id="auth-message" class="cloud-form-error" role="status"></p><button id="auth-submit" class="primary-button" type="submit">Sign in<i data-lucide="log-in"></i></button></form><p class="auth-note">Your session stays securely saved in this browser.</p></dialog>
 <dialog id="leaderboard-dialog" class="game-dialog wide-dialog" aria-labelledby="leaderboard-title"><div class="dialog-heading"><div><span class="eyebrow">GROWING TOGETHER</span><h2 id="leaderboard-title">The valley leaderboard</h2></div><button class="icon-button" data-cloud-close aria-label="Close"><i data-lucide="x"></i></button></div><p class="leaderboard-intro">Tap a farmer to see their profile. A green dot means online now.</p><details class="rank-drawer" id="rank-drawer"><summary><span class="rank-label" id="rank-label">Rank by</span><span class="rank-current" id="rank-current">${art(rankArtKey('level'))}<b>${LEADERBOARD_CATEGORIES.level.heading}</b></span><i class="rank-drawer-chevron" data-lucide="chevron-down" data-line-icon></i></summary><div class="leaderboard-filter" id="leaderboard-filter">${rankPickerMarkup(LEADERBOARD_CATEGORIES,art)}<input type="hidden" id="leaderboard-category" value="level"></div></details><p id="leaderboard-description">${LEADERBOARD_CATEGORIES.level.description}</p><div class="cloud-sync"><span id="cloud-status" role="status">Connecting…</span><button id="retry-cloud" class="back-button">Refresh</button></div><div id="leaderboard-results" aria-live="polite"></div><p class="cloud-privacy">Your name, online status and public farming achievements appear here. Your diamonds and farm details stay private.</p></dialog>
 <dialog id="username-dialog" class="game-dialog" aria-labelledby="username-title"><div class="dialog-heading"><div><span class="eyebrow">MEET THE OTHER FARMERS</span><h2 id="username-title">What should we call you?</h2></div><button class="icon-button" data-cloud-close aria-label="Keep playing"><i data-lucide="x"></i></button></div><p class="section-copy">Choose the display name other players will see on the leaderboard.</p><form id="username-form"><label for="username-input">Display name</label><input id="username-input" name="username" autocomplete="nickname" minlength="3" maxlength="20" required placeholder="Your farmer name"><small>3–20 letters, numbers, spaces, underscores or hyphens.</small><p id="username-error" class="cloud-form-error" role="alert"></p><button class="primary-button" type="submit"><span id="username-submit-label">Join the leaderboard</span><i data-lucide="arrow-right"></i></button></form></dialog>`;
 document.body.append(...holder.children);let mode='signin',nameFrom='leaderboard';
 // The leaderboard only ranks farmers; your own account (profile, name, sign out) lives at the top of Settings.
 const account=document.createElement('section');account.className='settings-account';account.setAttribute('aria-labelledby','settings-account-title');
 // Your farmer at a glance (avatar and name), an invitation to pick a real name while the game still uses the one it
 // made up at sign-up, and the three account buttons.
 account.innerHTML='<h3 class="settings-heading" id="settings-account-title">Your account</h3><div class="account-card"><img id="account-avatar" class="account-avatar" src="" alt="" width="56" height="56"><div class="account-who"><small>Farmer name</small><span id="player-name">Your farmer profile</span></div></div><div class="name-nudge" id="name-nudge" hidden><strong>Make the name your own</strong><p>You’re <b id="name-nudge-current"></b> for now. Pick a name other farmers will remember.</p><button class="primary-button" id="name-nudge-button" type="button">Choose my farmer name</button></div><div class="cloud-profile account-actions"><button class="small-button" id="view-player-profile">Your profile</button><button class="small-button" id="rename-player" hidden>Change name</button><button class="small-button" id="logout-player" hidden>Sign out</button></div>';
 const settings=$('sound-dialog');(settings?.querySelector('.dialog-heading')??document.body).after(account);
 function show(id){document.querySelectorAll('dialog[open]').forEach(d=>d.close());$(id).showModal();}function setMode(next){mode=next;document.querySelectorAll('[data-auth-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.authTab===mode)));$('register-name-row').hidden=mode!=='register';$('auth-username').required=mode==='register';$('auth-password').autocomplete=mode==='register'?'new-password':'current-password';$('auth-submit').innerHTML=mode==='register'?'Create account<i data-lucide="user-plus"></i>':'Sign in<i data-lucide="log-in"></i>';$('auth-message').textContent='';window.lucide?.createIcons();}function promptName(name=''){$('username-submit-label').textContent=nameFrom==='settings'?'Save my name':'Join the leaderboard';$('username-input').value=name;$('username-error').textContent='';show('username-dialog');$('username-input').focus();}
 document.querySelectorAll('[data-cloud-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>setMode(b.dataset.authTab));button.onclick=()=>{show('leaderboard-dialog');onOpen();};$('retry-cloud').onclick=onRetry;$('leaderboard-category').onchange=()=>{const key=$('leaderboard-category').value;$('leaderboard-description').textContent=LEADERBOARD_CATEGORIES[key].description;$('rank-current').innerHTML=`${art(rankArtKey(key))}<b>${LEADERBOARD_CATEGORIES[key].heading}</b>`;$('rank-drawer').open=false;onOpen();};bindRankPicker($('leaderboard-filter'),{categories:LEADERBOARD_CATEGORIES,field:$('leaderboard-category'),onChange:()=>$('leaderboard-category').onchange()});$('rename-player').onclick=()=>{nameFrom='settings';promptName($('player-name').dataset.username??'');};$('name-nudge-button').onclick=()=>{nameFrom='settings';promptName('');};$('username-dialog').addEventListener('close',()=>{nameFrom='leaderboard';});$('logout-player').onclick=onSignOut;$('view-player-profile').onclick=onPlayer;
 $('auth-form').onsubmit=async event=>{event.preventDefault();const submit=$('auth-submit');submit.disabled=true;$('auth-message').textContent=mode==='register'?'Creating your account…':'Signing in…';try{if(mode==='signin')await onSignIn($('auth-email').value,$('auth-password').value);else{const result=await onRegister($('auth-email').value,$('auth-password').value,$('auth-username').value);if(result.confirmationRequired){$('auth-message').textContent='Check your inbox and confirm your email address. You will be signed in automatically afterward.';return;}}$('auth-dialog').close();}catch(error){$('auth-message').textContent=error.message;}finally{submit.disabled=false;}};
 $('username-form').onsubmit=async event=>{event.preventDefault();const submit=event.currentTarget.querySelector('[type="submit"]');submit.disabled=true;$('username-error').textContent='';try{await onName($('username-input').value);if(nameFrom==='settings'&&settings){nameFrom='leaderboard';show('sound-dialog');}else{show('leaderboard-dialog');await onOpen();}}catch(error){$('username-error').textContent=error.message;}finally{submit.disabled=false;}};window.lucide?.createIcons();
 return {promptName,requireAuth(){if(!$('auth-dialog').open)show('auth-dialog');},authenticated(){if($('auth-dialog').open)$('auth-dialog').close();},configurationError(){show('auth-dialog');$('auth-message').textContent='The account connection has not been configured yet.';},authMessage(text){if($('auth-dialog').open)$('auth-message').textContent=text;},setProfile(profile,player){$('player-name').textContent=profile?profile.username:'Pick your farmer name';$('player-name').dataset.username=profile?.username??'';const madeUp=Boolean(player)&&isRandomPlayerName(profile?.username);$('name-nudge').hidden=!madeUp;$('name-nudge-current').textContent=profile?.username??'';$('rename-player').hidden=!player||madeUp;$('logout-player').hidden=!player;const avatar=playerAvatar(profile?.avatar_id);$('account-avatar').src=avatar.src;$('account-avatar').alt=avatar.name;},status(text){$('cloud-status').textContent=text;},message(text){const p=document.createElement('p');p.className='leaderboard-empty';p.textContent=text;$('leaderboard-results').replaceChildren(p);},get category(){return $('leaderboard-category').value;},get results(){return $('leaderboard-results');},get open(){return $('leaderboard-dialog').open;}};
}
