const $=id=>document.getElementById(id);
export function createCloudUI({onOpen,onName,onRetry,onSignIn,onRegister,onSignOut}){
 const button=document.createElement('button');button.id='leaderboard-button';button.className='leaderboard-button';button.setAttribute('aria-haspopup','dialog');button.innerHTML='<i data-lucide="trophy"></i><span>Leaderboard</span>';document.querySelector('.tool-dock').append(button);
 const holder=document.createElement('div');holder.innerHTML=`<dialog id="auth-dialog" class="game-dialog auth-dialog" aria-labelledby="auth-title"><div class="auth-brand"><img src="/assets/harvest-tycoon-logo.png" alt="" width="92" height="92"><div><span class="eyebrow">WELCOME BACK TO THE FARM</span><h2 id="auth-title">Save your progress</h2></div></div><p class="section-copy">Sign in to access your coins, level, and player name on any device.</p><div class="auth-tabs" role="tablist"><button type="button" role="tab" data-auth-tab="signin" aria-selected="true">Sign in</button><button type="button" role="tab" data-auth-tab="register" aria-selected="false">Create account</button></div><form id="auth-form"><div id="register-name-row" hidden><label for="auth-username">Player name</label><input id="auth-username" autocomplete="nickname" minlength="3" maxlength="20" placeholder="Sunny Acres"></div><label for="auth-email">Email address</label><input id="auth-email" type="email" autocomplete="email" required placeholder="you@example.com"><label for="auth-password">Password</label><input id="auth-password" type="password" autocomplete="current-password" minlength="6" required><p id="auth-message" class="cloud-form-error" role="status"></p><button id="auth-submit" class="primary-button" type="submit">Sign in<i data-lucide="log-in"></i></button></form><p class="auth-note">Your session stays securely saved in this browser.</p></dialog>
 <dialog id="leaderboard-dialog" class="game-dialog wide-dialog" aria-labelledby="leaderboard-title"><div class="dialog-heading"><div><span class="eyebrow">GROWING TOGETHER</span><h2 id="leaderboard-title">The valley leaderboard</h2></div><button class="icon-button" data-cloud-close aria-label="Close"><i data-lucide="x"></i></button></div><p class="leaderboard-intro">The top 20 farmers by current coins. Shared scores, personal farms.</p><div class="cloud-profile"><span id="player-name">Your farmer profile</span><button class="small-button" id="rename-player" hidden>Change name</button><button class="small-button" id="logout-player" hidden>Sign out</button></div><div class="cloud-sync"><span id="cloud-status" role="status">Connecting…</span><button id="retry-cloud" class="back-button">Refresh</button></div><div id="leaderboard-results" aria-live="polite"></div><p class="cloud-privacy">Your player name, coins, and level are linked to your account and shared on the leaderboard.</p></dialog>
 <dialog id="username-dialog" class="game-dialog" aria-labelledby="username-title"><div class="dialog-heading"><div><span class="eyebrow">MEET THE OTHER FARMERS</span><h2 id="username-title">What should we call you?</h2></div><button class="icon-button" data-cloud-close aria-label="Keep playing"><i data-lucide="x"></i></button></div><p class="section-copy">Choose the display name other players will see on the leaderboard.</p><form id="username-form"><label for="username-input">Display name</label><input id="username-input" name="username" autocomplete="nickname" minlength="3" maxlength="20" required placeholder="Sunny Acres"><small>3–20 letters, numbers, spaces, underscores or hyphens.</small><p id="username-error" class="cloud-form-error" role="alert"></p><button class="primary-button" type="submit">Join the leaderboard<i data-lucide="arrow-right"></i></button></form></dialog>`;
 document.body.append(...holder.children);let mode='signin';
 function show(id){document.querySelectorAll('dialog[open]').forEach(d=>d.close());$(id).showModal();}function setMode(next){mode=next;document.querySelectorAll('[data-auth-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.authTab===mode)));$('register-name-row').hidden=mode!=='register';$('auth-username').required=mode==='register';$('auth-password').autocomplete=mode==='register'?'new-password':'current-password';$('auth-submit').innerHTML=mode==='register'?'Create account<i data-lucide="user-plus"></i>':'Sign in<i data-lucide="log-in"></i>';$('auth-message').textContent='';window.lucide?.createIcons();}function promptName(name=''){$('username-input').value=name;$('username-error').textContent='';show('username-dialog');$('username-input').focus();}
 document.querySelectorAll('[data-cloud-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>setMode(b.dataset.authTab));button.onclick=()=>{show('leaderboard-dialog');onOpen();};$('retry-cloud').onclick=onRetry;$('rename-player').onclick=()=>promptName($('player-name').dataset.username??'');$('logout-player').onclick=onSignOut;
 $('auth-form').onsubmit=async event=>{event.preventDefault();const submit=$('auth-submit');submit.disabled=true;$('auth-message').textContent=mode==='register'?'Creating your account…':'Signing in…';try{if(mode==='signin')await onSignIn($('auth-email').value,$('auth-password').value);else{const result=await onRegister($('auth-email').value,$('auth-password').value,$('auth-username').value);if(result.confirmationRequired){$('auth-message').textContent='Check your inbox and confirm your email address. You will be signed in automatically afterward.';return;}}$('auth-dialog').close();}catch(error){$('auth-message').textContent=error.message;}finally{submit.disabled=false;}};
 $('username-form').onsubmit=async event=>{event.preventDefault();const submit=event.currentTarget.querySelector('[type="submit"]');submit.disabled=true;$('username-error').textContent='';try{await onName($('username-input').value);show('leaderboard-dialog');await onOpen();}catch(error){$('username-error').textContent=error.message;}finally{submit.disabled=false;}};window.lucide?.createIcons();
 return {promptName,requireAuth(){if(!$('auth-dialog').open)show('auth-dialog');},authenticated(){if($('auth-dialog').open)$('auth-dialog').close();},configurationError(){show('auth-dialog');$('auth-message').textContent='The account connection has not been configured yet.';},authMessage(text){if($('auth-dialog').open)$('auth-message').textContent=text;},setProfile(profile,player){$('player-name').textContent=profile?profile.username:'Pick your farmer name';$('player-name').dataset.username=profile?.username??'';$('rename-player').hidden=!player;$('logout-player').hidden=!player;},status(text){$('cloud-status').textContent=text;},message(text){const p=document.createElement('p');p.className='leaderboard-empty';p.textContent=text;$('leaderboard-results').replaceChildren(p);},get results(){return $('leaderboard-results');},get open(){return $('leaderboard-dialog').open;}};
}
